container:
  image: circleci/node:12-browsers

task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  matrix:
    - name: Test
      test_script: yarn test